drug_types_list = (
    ('pills','PILLS'),
    ('pellets','PELLETS'),
    ('lozenges','LOZENGES'),
    ('tablets', 'TABLETS'),
    ('capsules','CAPSULES'),
    ('liquid','LIQUID'),
    ('inhalants','INHALANTS'),
    ('ointments', 'OIMENTS'),
    ('liniment', 'LINIMENT'),
    ('sprays', 'SPRAYS'),
    ('lotions', 'LOTIONS'),
    ('paste', 'PASTE'),
    ('powder', 'POWDER'),
    ('emulsions', 'EMULSIONS'),
    ('gels', 'GELS'),
    ('magmas', 'MAGMAS'),
    ('mixtures', 'MIXTURES'),
)