# Generated by Django 3.2.7 on 2021-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('drug_type', models.CharField(choices=[('pills', 'PILLS'), ('pellets', 'PELLETS'), ('lozenges', 'LOZENGES'), ('tablets', 'TABLETS'), ('capsules', 'CAPSULES'), ('liquid', 'LIQUID'), ('inhalants', 'INHALANTS'), ('ointments', 'OIMENTS'), ('liniment', 'LINIMENT'), ('sprays', 'SPRAYS'), ('lotions', 'LOTIONS'), ('paste', 'PASTE'), ('powder', 'POWDER'), ('emulsions', 'EMULSIONS'), ('gels', 'GELS'), ('magmas', 'MAGMAS'), ('mixtures', 'MIXTURES')], default='pills', max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('exp', models.DateField()),
                ('mfg', models.DateField()),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
