# Generated by Django 3.2.7 on 2021-10-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='exp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='mfg',
            field=models.DateField(auto_now_add=True),
        ),
    ]
