# Generated by Django 3.2.7 on 2021-10-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20211005_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(error_messages={'unique': 'This drug id has already been registered.'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_type',
            field=models.CharField(blank=True, choices=[('pills', 'PILLS'), ('pellets', 'PELLETS'), ('lozenges', 'LOZENGES'), ('tablets', 'TABLETS'), ('capsules', 'CAPSULES'), ('liquid', 'LIQUID'), ('inhalants', 'INHALANTS'), ('ointments', 'OIMENTS'), ('liniment', 'LINIMENT'), ('sprays', 'SPRAYS'), ('lotions', 'LOTIONS'), ('paste', 'PASTE'), ('powder', 'POWDER'), ('emulsions', 'EMULSIONS'), ('gels', 'GELS'), ('magmas', 'MAGMAS'), ('mixtures', 'MIXTURES')], default='pills', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='exp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='mfg',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drug',
            name='updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
