# Generated by Django 3.2.7 on 2021-10-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20211007_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='exp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='mfg',
            field=models.DateField(null=True),
        ),
    ]
