# Generated by Django 3.2.7 on 2021-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20211007_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='mfg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
